temperature/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.urls import path
from . import views

app_name = 'temperature'
urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('', views.ChartFormView.as_view(), name='chart_form_view'),
    path('list', views.TemperatureListView.as_view(), name='list_view'),
]

temperature_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('temperature.urls')),
    path('admin/', admin.site.urls),
]

temperature/models.py
from datetime import datetime
from django.db import models
from django.contrib import admin
from django.core.exceptions import ValidationError

class City(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'cities'
        ordering = ['name']


class CityTemperature(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    date = models.DateTimeField('date measured')
    temperature_value = models.IntegerField(default=0)

    @admin.display(description='Temperature')
    def temperature_str(self):
        temperature_str = ''
        if self.temperature_value > 0:
            temperature_str = '+{0}°C'.format(self.temperature_value)
        else:
            temperature_str = '{0}°C'.format(self.temperature_value)
        return temperature_str

    def __str__(self):
        return '{0} - {1} {2}'.format(
            self.city.name,
            self.date.strftime('%d.%m.%Y %H:%M'),
            self.temperature_str()
        )

    def validate_unique(self, exclude=None):
        queryset = CityTemperature.objects.filter(
            city = self.city,
            date__year = self.date.year,
            date__month = self.date.month,
            date__day = self.date.day,
            date__hour = self.date.hour
        )
        if queryset.exists() and self.pk != queryset[0].pk:
            raise ValidationError('Data already exists for this City and hour')
        return super(CityTemperature, self).validate_unique(exclude=exclude)

    def save(self, *args, **kwargs):
        self.date = datetime(self.date.year, self.date.month, self.date.day, self.date.hour)
        super(CityTemperature, self).save(*args, **kwargs)
    
    class Meta:
        db_table = 'city_temperatures'
        ordering = ['date']
        unique_together = ('city', 'date')

temperature/forms.py
from django import forms
from .models import City
from bootstrap_datepicker_plus.widgets import DatePickerInput

class TemperatureChartForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all().order_by('name'))
    date = forms.DateField(
        widget = DatePickerInput(format='%d.%m.%Y'),
        input_formats = ('%d.%m.%Y', )
    )

class TemperatureFilterForm(forms.Form):
    city = forms.ModelChoiceField(queryset=City.objects.all().order_by('name'), required=False)
    date = forms.DateField(
        widget = DatePickerInput(format='%d.%m.%Y'),
        input_formats = ('%d.%m.%Y', ),
        required = False
    )

temperature/views.py
from django.views import generic
from django.http import JsonResponse
from .models import CityTemperature 
from .forms import TemperatureChartForm, TemperatureFilterForm

class ChartFormView(generic.FormView):
    template_name = 'main_form.html'
    form_class = TemperatureChartForm

    def form_invalid(self, form):
        return JsonResponse({'error': True, 'error': form.errors})

    def form_valid(self, form):
        city = form.cleaned_data['city']
        date = form.cleaned_data['date']
        labels = []
        data = []
        queryset = CityTemperature.objects.all().filter(
            city = city,
            date__year = date.year,
            date__month = date.month,
            date__day = date.day
        ).order_by('date')
        for city_temperature in queryset:
            labels.append(city_temperature.date.strftime('%H:%M'))
            data.append(city_temperature.temperature_value)
        
        return JsonResponse(data = {
            'success': True,
            'labels': labels,
            'data': data,
        })


class TemperatureListView(generic.ListView):
    template_name = 'list_view.html'
    paginate_by = 10
    model = CityTemperature
    context_object_name = 'temperature_list'

    def get_context_data(self, **kwargs):
        context = super(TemperatureListView, self).get_context_data(**kwargs)
        context['form'] = TemperatureFilterForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = self.model.objects.all().order_by('date')
        form = TemperatureFilterForm(self.request.GET)
        if (form.is_valid()):
            city = form.cleaned_data['city']
            if (city):
                queryset = queryset.filter(city=city)
            date = form.cleaned_data['date']
            if (date):
                queryset = queryset.filter(
                    date__year = date.year,
                    date__month = date.month,
                    date__day = date.day
                )
        return queryset

temperature/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'js/chart.min.js' %}"></script>

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {{ form.media }}

    <title>Temperature app</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        {% include 'navigation.html' %}
    </header>
    <main>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
          <span class="text-muted">Sample Django application {% now "Y" %}</span>
        </div>
      </footer>
</body>
</html>

temperature/templates/list_view.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-md-12">
            <form action="" method="get" class="form" id="main-form">
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Show data</button>
            </form>
        </div>
    </div>
    
    <table id="temperature-table" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th scope="col">City</th>
                <th scope="col">Date</th>
                <th scope="col">Hour</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            {% for datarow in temperature_list %}
            <tr>
                <td>{{datarow.city}}</td>
                <td>{{datarow.date|date:"d.m.Y"}}</td>
                <td>{{datarow.date|date:"H:i"}}</td>
                <td>{{datarow.temperature_str}}</td>
            </tr>
            {% endfor %}
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                <a class="btn btn-light" href="?{% param_replace page=1 %}">First</a>
                <a class="btn btn-light" href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <a class="btn btn-primary" href="?{% param_replace page=num %}"> {{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-light" href="?{% param_replace page=num %}"> {{ num }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="btn btn-light" href="?{% param_replace page=page_obj.next_page_number %}">Next</a>
                    <a class="btn btn-light" href="?{% param_replace page=paginator.num_pages %}">Last</a>
                {% endif %}
    
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock content %}

temperature/templates/main_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-md-12">
            <div class="alert alert-danger error-msg" style="display:none">
                <ul></ul>
            </div>
            <form action="" method="post" class="form" id="main-form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Show data</button>
            </form>
        </div>
    </div>
    <div class="row my-3">
        <div id="empty-data" class="alert alert-warning" role="alert" style="display:none">
            Sorry, no data
        </div>
        <div id="container" style="width: 75%;">
            <canvas id="temperature-chart"></canvas>
        </div>
    </div>
    <script src="{% static 'js/main_form.js' %}"></script>
</div>
{% endblock %}

temperature/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Temperature app</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link" href="/">Main</a>
            <a class="nav-link" href="{% url 'temperature:list_view' %}">Table</a>
            <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
        </div>
    </div>
</nav>